### PR TITLE
Distance metrics

### PR DESCRIPTION
**Pull request by pknight24**
# Implements Jaccard and Hellinger distances for AbstractAbundanceTable

These commits add methods for computing the Jaccard and Hellinger distances for the AbstractAbundanceTable type. I find myself using these relatively often, and figured it would be helpful to write a quick implementation for this package.

I tried to be a thorough as possible, but if anything is missing or incorrect, please let me know and I'll be sure to make any necessary changes.

Thanks!
Parker

## Types of changes

This PR implements the following changes:

* [-] :sparkles: New feature (A non-breaking change which adds functionality).
* [ ] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :ballot_box_with_check: Checklist

- [-] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [-] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [-] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [-] :ok: There are unit tests that cover the code changes I have made.
- [-] :ok: The unit tests cover my code changes AND they pass.
- [ ] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [-] :ok: All changes should be compatible with the latest stable version of Julia.
- [ ] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by kescobo** [comment]
Awesome, looks great! Well get it merged as soon as I'm at my laptop. 2 things:

1. Can you double check that the docstrings will be built (they should be somewhere in a `@docs` block somewhere in `docs/src/...`)
2. Can you increment the version number in `Project.toml`?

**Comment by pknight24** [comment]
This commit bumps the version number to 0.8.0. The docstrings are included in the `@docs` block in`docs/src/diversity.md`.

**Comment by kescobo** [comment]
Oh sorry - just the patch version (so 0.7.1). Prior to v1.0, changes to the middle number indicate breaking changes, but since this is just adding some stuff, it shouldn't break anything. Apologies for not being clear 🤦‍♂️

**Comment by pknight24** [comment]
No worries! Fixing now.

**Review by kescobo — APPROVED** [review]

**Comment by kescobo** [comment]
Alright - new version tagged and merged! Thanks for the contribution :pray:

**Pull request merged**
